server:
  name: kratos-layout # 注册服务名
  environment: dev # 所处环境同时也是 nacos namespace
# 注册中心&配置中心
nacos:
  configuration: # 配置中心地址
    ip: 127.0.0.1 # Nacos配置中心IP
    port: 8848 # Nacos配置中心端口
    extension: yaml #指定yaml格式的配置
    group: DEFAULT_GROUP # 指定分组
    timeout_ms: 5000
    username: nacos
    password: nacos